### ISSUE TITLE
html_to_txt_pyautogui.py closes after selection of folder that has message.html files

### ISSUE THREAD

**Issue by reiyusmolket** [lilium895/Telegram-chat-restorer-pyautogui-version#1]
Hi, I tried using this but when I run the html_to_txt_pyautogui.py file, it prompts me to ask me where the html files are, and then when added the python window disappears and no txt files are created:
![Screenshot 2024-07-12 040204](https://github.com/lilium895/Telegram-chat-restorer-pyautogui-version/assets/175355222/e10b101d-60ad-4948-9bb5-ed3b5f073a3c)

I have added the bs4 folder from BeautifulSoup into the main file
![Screenshot 2024-07-12 040115](https://github.com/lilium895/Telegram-chat-restorer-pyautogui-version/assets/175355222/229f3595-13c8-442e-bdce-6f18b69b6d6c)

Any help is very much appreciated, thanks!

**Comment by lilium895** [comment]
I've made some changes in the code, if you want to try again. The text version of the chat should be in the 
C:\Users\*YOUR_USER_NAME* folder
Don't worry to tell me if you still have issues.
I'm sorry if the code is not that user friendly.

**Comment by reiyusmolket** [comment]
Thank you for replying, it means so much to me!

I installed the pip bits, my bad. Am very new to coding. The new version that you've written goes to ask me how many files it has to process, but then there is a substring error after.
![Screenshot 2024-07-12 112929](https://github.com/user-attachments/assets/85409426-09f2-469e-9114-40f069c6803d)

Is there anything I'm missing?

**Comment by lilium895** [comment]
It looks like the program found a media whose name doesn't start with chat_ 

When someone sends a media in a message it usually looks like this in the html:

User1
       </div>

       <div class="media_wrap clearfix">

        <a class="photo_wrap clearfix pull_left" href="../../chats/chat_1/photos/photo_2@23-05-2020_21-32-29.jpg">
        
The code should select the content of the href and remove all the gibberish before the actual name of the file. Name that you will need after, when the second program will have to search it in the folder and send it.

Try to send me that part. Careful about sensitive information.
You have to open the message.html file (I believe it is the first one) with Notepad.
Look for 'media with the hotkey ctrl+F and look what is inside the href.
We probably have to change the code to make it work for your format.

**Comment by reiyusmolket** [comment]
Ah, that might be the stickers that I didn't export:

```
<div class="media_wrap clearfix">
<div class="media clearfix pull_left media_photo">
<div class="fill pull_left"></div>
<div class="body">
<div class="title bold">Sticker</div>
<div class="description">Not included, change data exporting settings to download.</div>
<div class="status details">😛, 10.2 KB</div>

```
This in comparison is my picture code:

```
<div class="media_wrap clearfix">
<a class="photo_wrap clearfix pull_left" href="photos/photo_1@30-01-2024_14-58-00.jpg">
<img class="photo" src="photos/photo_1@30-01-2024_14-58-00_thumb.jpg" style="width: 260px; height: 117px"/>
</a>
</div>
```

Is this something fixable?

**Comment by lilium895** [comment]
Yeah, I think so. You have to change the code by removing these lines:

                    #remove chat_01 before file name
                    i=media.index("chat_")
                    media=media[i+8:]
                    
It's not about the sticker, it's about that it can't find the substring "chat_".
In that part of the code media.index() finds the index of the substring "chat_" in the long string "photos/photo_1@30-01-2024_14-58-00.jpg" in href. As you see "chat_" isn't in there, so it gives you error.

Happy to help, don't be shy to ask more

**Comment by reiyusmolket** [comment]
Ahh I see. Hmm at the end I wasn't able to get it to work still, and my friend told me to just leave it haha. Thanks a lot though!

**Comment by reiyusmolket** [comment]
Ahh I see. Hmm at the end I wasn't able to get it to work still, and my friend told me to just leave it haha. Thanks a lot though!

**Comment by lilium895** [comment]
I'm sorry to hear that. I know that my project isn't that easy to use, but, as I said in the preview, it works.
If you will ever want to re-try, maybe with my help, I'll be happy to help you and write some lines of code.
Good luck with your project!

(just for making you re-think about it, I think that your html chat must be different from mine and Suberbia's (another gituser).
It's not that difficult to parse the html file with beautiful soup to get the informations you need. Maybe there are already in github some of these methods. I'll be happy to follow you with every error if you want to try it again.)
